swagger: '2.0'
info:
  title: Brauprotokoll API
  description: Protokollierung des Brauprozesses
  version: "1.0.0"
  contact:
    name: API Support
    url: http://myUrl/support
    email: trichling@thinkexception.net
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

host: 127.0.0.1:8000

schemes:
  - http

basePath: /v1/api

consumes:
  - application/json

produces:
  - application/json 
  
paths:
  /protokolle:
    get:
      summary: Liste aller Brauprotokolle
      description: |
        Gibt eine Liste aller Brauprotokolle zurück.
      tags:
        - Brauprotokolle
      responses:
        200:
          description: Eine Liste aller Brauprotokolle
          schema:
            type: array
            items:
              $ref: '#/definitions/brauprotokollRepresentation'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
            
    post:
      summary: Ein neues Brauprotokoll anlegen
      description: |
        Ermöglicht das erstellen eines neuen Brauprotokolls. Die Angabe der Id ist nicht erforderlich, diese wird automatisch generiert.
      tags:
        - Brauprotokolle
      parameters:
        - name: protokoll
          description: Daten zum zu erstellenden Brauprotokoll.
          in: body
          required: true
          schema:
            $ref: '#/definitions/brauprotokollRepresentation'
      responses:
        201:
          description: Das Brauprotokoll wurde angelegt.
          headers:
            Location:
              description: Die URL des erzeugten Brauprotokolls
              type: string
          schema:
            $ref: '#/definitions/brauprotokollRepresentation'
          
  /protokolle/{id}:
    parameters:
      - name: id
        in: path
        description: ID des Brautprokolls
        required: true
        type: string
      
    get:
      summary: Zeigt Details zu einem Brauprotokoll an
      description: |
        Gibt einen logbuchartigen Überblick über einen bestimmten Brauvorgang
      tags:
        - Brauprotokolle
      responses:
        200:
          description: Details zu einem Brauprzoess
          schema:
              $ref: '#/definitions/brauprotokollRepresentation'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
      
    put:
        summary: Ein bestehendes Brauprotokoll ändern.
        description: |
          Ermöglicht die Änderung eines bereits bestehenden Brauprotokolls. Die Id kann nicht geändert werden. Wenn bereits weitergehende Daten des Protokolls geändert worden sind, kann nur noch der Name geändert werden.
        tags:
          - Brauprotokolle
        parameters:
          - name: protokoll
            description: Die zu ändernden Daten des Brauprotokolls.
            in: body
            required: true
            schema:
              $ref: '#/definitions/brauprotokollRepresentation'
        responses:
          200:
            description: Die übergebenen Daten wurden aktualisiert. Die Antwort enthält die aktualisierte Ressource.
            schema:
              $ref: '#/definitions/brauprotokollRepresentation'
   
  /protokolle/{id}/vorbereitung:
    parameters:
      - name: id
        in: path
        description: ID des Brautprokolls
        required: true
        type: string
        
    get:
      summary: Checkliste für die Vorbereitung des Brautags
      description: |
        Zeigt die Checkliste der notwendigen Schritte die vor der Durchführung des Brautags erledigt werden müssen.
      tags:
        - Vorbereitungen
      responses:
        200:
          description: Die Checkliste der Vorbereitungen
          schema:
            $ref: '#/definitions/vorbereitungChecklisteRepresentation'
    
    put:
      summary: Legt eine neue Checkliste an.
      description: |
        Es wird eine neue Checkliste angelegt. Der Entity-Body wird ignoriert. Diese Methode ist nur zur Unterstützung beim Mocken mit Swagger Server.
      tags:
        - Vorbereitungen
      parameters:
        - name: checkliste
          in: body
          schema:
            $ref: '#/definitions/vorbereitungChecklisteRepresentation'
          description: Die neue Checkliste.
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/vorbereitungChecklisteRepresentation'
    
    patch:
      summary: Einen Punkt der Checkliste als erledigt markieren.
      description: |
        Mit dieser Methode kann ein Element der Checkliste als erledigt markiert werden.
      tags:
        - Vorbereitungen
      parameters:
        - name: checklistenEintrag
          in: body
          schema:
            $ref: '#/definitions/vorbereitungChecklisteRepresentation'
          description: Der Name des Checklisteneintrags der erledigt wurde.
      responses:
        200:
          description: Der Punkt wurde erfolgreich als erledigt markiert
          schema: 
            $ref: '#/definitions/vorbereitungChecklisteRepresentation'
            
  /protokolle/{id}/maischen:
    parameters:
      - name: id
        in: path
        description: ID des Brautprokolls
        required: true
        type: string
        
    get:
      summary: Zeigt das den Verlauf des Maischens
      tags:
        - Maischen
      responses:
        200:
          description: Die Liste der Logeinträge zum Maischeverlauf
          schema:
            $ref: '#/definitions/maischenLogRepresentation'
            
  /protokolle/{id}/maischen/rast:
    parameters:
      - name: id
        in: path
        description: ID des Brautprokolls
        required: true
        type: string
        
    post:
      summary: Einen neue Rast im Maischprotokoll hinzufügen
      tags:
        - Maischen
      parameters:
        - name: eintrag
          in: body
          schema:
            $ref: '#/definitions/maischenLogEintragRastRepresentation'
      responses:
        201:
          description: Eintrag wurde angelegt.
          schema:
            $ref: '#/definitions/maischenLogEintragRastRepresentation'
  
  /protokolle/{id}/maischen/aufheizen:
    parameters:
      - name: id
        in: path
        description: ID des Brautprokolls
        required: true
        type: string
        
    post:
      summary: Einen neue Aufheizphase im Maischprotokoll hinzufügen
      tags:
        - Maischen
      parameters:
        - name: eintrag
          in: body
          schema:
            $ref: '#/definitions/maischenLogEintragAufheizeRepresentation'
      responses:
        201:
          description: Eintrag wurde angelegt.
          schema:
            $ref: '#/definitions/maischenLogEintragAufheizeRepresentation'
  
  /protokolle/{id}/laeutern:
    parameters:
      - name: id
        in: path
        description: ID des Brautprokolls
        required: true
        type: string
        
    get:
      summary: Zeigt das den Verlauf des Läuterns
      tags:
        - Laeutern
      responses:
        200:
          description: Die Liste der Logeinträge zum Läuterverlauf
          schema:
            $ref: '#/definitions/laeuternLogRepresentation'
              
    post:
      summary: Einen neuen Eintrag im Läuterprotokoll hinzufügen
      tags:
        - Laeutern
      parameters:
        - name: eintrag
          in: body
          schema:
            $ref: '#/definitions/laeuternLogEintragRepresentation'
      responses:
        201:
          description: Eintrag wurde angelegt.
          schema:
            $ref: '#/definitions/laeuternLogEintragRepresentation'
            
  /protokolle/{id}/kochen:
    parameters:
      - name: id
        in: path
        description: ID des Brautprokolls
        required: true
        type: string
        
    get:
      summary: Zeigt das den Verlauf des Kochens
      tags:
        - Kochen
      responses:
        200:
          description: Die Liste der Logeinträge zum Kochverlauf
          schema:
            $ref: '#/definitions/kochenLogRepresentation'
              
    post:
      summary: Einen neuen Eintrag im Kochprotokoll hinzufügen
      tags:
        - Kochen
      parameters:
        - name: eintrag
          in: body
          schema:
            $ref: '#/definitions/kochenLogEintragRepresentation'
      responses:
        201:
          description: Eintrag wurde angelegt.
          schema:
            $ref: '#/definitions/kochenLogEintragRepresentation'
  
  /protokolle/{id}/ausschlagen:
    parameters:
      - name: id
        in: path
        description: ID des Brautprokolls
        required: true
        type: string
        
    get:
      summary: Zeigt die Übersicht über das Ausschlagen, Hopfenseihen und Kühlen
      tags:
        - Ausschlagen
      responses:
        200:
          description: Die Liste der Logeinträge zum Kochverlauf
          schema:
            $ref: '#/definitions/ausschlagenRepresentation'
    
    put:
      summary: Legt einen neuen Detaildatensatz an.
      tags:
        - Ausschlagen
      description: |
        Es wird ein neuer Detaildatensatz angelegt. Der Entity-Body wird ignoriert. Diese Methode ist nur zur Unterstützung beim Mocken mit Swagger Server.
      parameters:
        - name: detail
          in: body
          schema:
            $ref: '#/definitions/ausschlagenRepresentation'
          description: Die neue Checkliste.
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/ausschlagenRepresentation'
    
    patch:
      summary: Ergänzt einen Eintrag in den Details zum Ausschlagen, Kühlen, Anstellen
      tags:
        - Ausschlagen
      parameters:
        - name: detail
          in: body
          schema:
            $ref: '#/definitions/ausschlagenRepresentation'
      responses:
        200:
          description: Information wurde hinzugefügt.
          schema: 
            $ref: '#/definitions/ausschlagenRepresentation'
                
definitions:
  brauprotokollRepresentation:
    type: object
    properties:
      id:
        type: string
        description: Eindeutiger Bezeichner dieses Brauprotokolls
      title:
        type: string
        description: Name des Brauvorhabens
      brautag:
        type: string
        format: date-time
        description: Datum des Brautags
      biername:
        type: string
        description: Der Name des zu brauenden Bieres
      stammwuerze:
        type: number
        format: double
        description: Die gewünschte Stammwürze des Bieres
    required:
      - title
      - brautag
      - biername
      - stammwuerze
        
  vorbereitungChecklisteRepresentation:
    type: object
    properties:
      brautag_angemeledet:
        type: boolean
        description: Wurde der Brautag beim zuständigen Hauptzollamt angemeldet?
      brautag_angemledet_am:
        type: string
        format: date-time
        description: Wann wurde der Brautag beim zuständigen Hauptzollamt angemeldet?
      rezept_festgegelgt:
        type: boolean
        description: Wurde das Rezept für den Brautag bereits festgelegt?
      rezept_festgegelgt_am:
        type: string
        format: date-time
        description: Wann wurde das Rezept festgelegt?
      zutaten_bestellt:
        type: boolean
        description: Wurde die Zutaten bereits bestellt?
      zutaten_bestellt_am:
        type: string
        format: date-time
        description: Wann wurde die Zutaten bestellt?
      zutaten_geliefert:
        type: boolean
        description: Wurde die Zutaten bereits geliefert?
      zutaten_geliefert_am:
        type: string
        format: date-time
        description: Wann wurde die Zutaten geliefert?
  
  maischenLogRepresentation:
    properties:
      eintraege:
        type: array
        items: 
          $ref: '#/definitions/maischenLogEintragRepresentation'
    
  maischenLogEintragRepresentation:
    type: object
    discriminator: artDesEintrags
    properties:
      artDesEintrags:
        type: string
      zeitpunkt:
        type: string
        format: date-time
        description: Der Zeitpunkt dieses Logeintrags. Wird beim automatisch generiert.
      kommentar:
        type: string
        description: Weitere Informationen, z. B. Rast verlängert oder Jodnormal
  
  maischenLogEintragRastRepresentation:
    allOf:
      - $ref: '#/definitions/maischenLogEintragRepresentation'
      - type: object
        properties:
          name:
            type: string
            description: Der Name der Rast, z. B. Eiweißrast, Maltoserast, Verzuckerungsrast.
          temparaturVon:
            type: number
            format: decimal
            description: Die untere Grenze des Temperaturbereichs der Rast 
          temparaturBis:
            type: number
            format: decimal
            description: Die obere Grenze im Temperaturbereich der Rast
          dauer:
            type: number
            format: int32
            description: Die Länge der Rast in Minuten

  maischenLogEintragAufheizeRepresentation:
    allOf:
      - $ref: '#/definitions/maischenLogEintragRepresentation'
      - type: object
        properties:
          rastBeiZieltemperatur:
            type: string
            description: Der Name der Rast zu deren Temperatur aufgeheizt werden soll.
          zieltemperatur:
            type: number
            format: decimal
            description: Die Zieltemperatur zu der aufgeheizt werden soll. 
      
  laeuternLogRepresentation:
    properties:
      eintraege:
        type: array
        items: 
          $ref: '#/definitions/laeuternLogEintragRepresentation'
      
  laeuternLogEintragRepresentation:
    type: object
    properties:
      zeitpunkt:
        type: string
        format: date-time
      temperatur:
        type: number
        format: decimal
      stammwuerze:
        type: number
        format: decimal
      liter:
        type: number
        format: decimal
      messort:
        type: string
        description: Wo wurde die Probe zur Messung genommen? Würze oder Nachlauf.
  
  kochenLogRepresentation:
    properties:
      eintraege:
        type: array
        items: 
          $ref: '#/definitions/kochenLogEintragRepresentation'
          
  kochenLogEintragRepresentation:
    type: object
    properties:
      zeitpunkt:
        type: string
        format: date-time
      hopfengabe:
        type: string
        description: Die Hopfensorte die zugegeben wird.
      menge:
        type: number
        description: Die Hopfenmenge in Gramm.
      bemerkung:
        type: string
        description: Zusätzliche Informationen, z. B. Vorderwürzehopfung oder Kochbeginn.
  
  ausschlagenRepresentation:
    type: object
    properties:
      ausschlagwuerze:
        type: number
        format: decimal
        description: Die Menge der heißen Würze mitsamt Hopfentreber
      beginnKuehlen:
        type: string
        format: date-time
        description: Der Zeitpunkt zu dem das Hopfenseihen / Kühlen beginnt.
      endeKuehlen:
        type: string
        format: date-time
        description: Der Zeitpunkt zu dem das Kühlen beendet ist
      anstellwuerze:
        type: number
        format: decimal
        description: Die Menge der gekühlten, anstellfähigen Würze
      zeitpunktAnstellen:
        type: string
        format: date-time
        description: Der Zeitpunkt zu dem die Würze angestellt wurde.
        
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
